name: Continuous integration
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cargo-cache
        with:
          key: build-${{ github.ref || github.run_id }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: ./.github/actions/bevy-setup
      - run: cargo build

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cargo-cache
        with:
          key: build-wasm-${{ github.ref || github.run_id }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: ./.github/actions/bevy-setup
      - name: Install trunk
        run: wget -qO- "https://github.com/thedodd/trunk/releases/download/v$VERSION/trunk-x86_64-unknown-linux-gnu.tar.gz" | tar -xzf-
        env:
          VERSION: 0.17.1
      - run: trunk build --release --public-url /${{ github.event.repository.name }}
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"

  deploy-pages:
    needs: build-wasm
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
